name = "slack-restaurant-picker"
main = "src/index.js"
compatibility_date = "2023-03-14"
account_id = "dffbae8a1ff9994ce7257013e54fe1b9" # EDIT

[vars]
APP_NAME = "Restaurant Picker"
APP_ENDPOINT = "https://slack-restaurant-picker.<your-workers-domain>" # EDIT